version: '3'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production node server.js
    volumes:
      - ./app:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: sh -c 'node server.js'
    tty: true

